name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Wait for LintAndTest to succeed
          uses: lewagon/wait-on-check-action@v1.0.0
          with:
            ref: ${{ github.ref }}
            check-name: 'LintAndTest'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            wait-interval: 10

        - uses: actions/checkout@v3

        - name: Validate tag version
          run: |
            version=$(cat version.txt)                # get version
            tag=${GITHUB_REF/refs\/tags\//}           # get tag name
            tag="${tag:1}"                            # remove the 'v' prefix from the tag that triggered this action
            echo "version: $version"
            echo "tag: $tag"
            if [ "$tag" == "$version" ]
            then
              echo "Tag and version are equal"
            else
              echo "Error: Tag and version are not equal, cannot create a release"
              exit 1
            fi

        - name: Build
          run: |
            chmod +x ./build.sh
            ./build.sh

        - name: Create Release and Upload Artifacts
          uses: ncipollo/release-action@v1
          with:
            artifacts: "dist/*"
            token: ${{ secrets.GITHUB_TOKEN }}
