name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
        - name: Wait for LintAndTest to succeed
          uses: lewagon/wait-on-check-action@v1.0.0
          with:
            ref: ${{ github.ref }}
            check-name: 'LintAndTest'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            wait-interval: 10

        - uses: actions/checkout@v3

        - name: Validate tag version
          run: |
            version=$(cat version.txt)                # get version
            tag=${GITHUB_REF/refs\/tags\//}           # get tag name
            tag="${tag:1}"                            # remove the 'v' prefix from the tag that triggered this action
            echo "version: $version"
            echo "tag: $tag"
            if [ "$tag" == "$version" ]
            then
              echo "Tag and version are equal"
            else
              echo "Error: Tag and version are not equal, cannot create a release"
              exit 1
            fi

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            echo "Installing requirements.txt and test_requirements.txt:"
            cd src
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            cd ../tests
            if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
            cd ..

        - name: Build
          run: |
            chmod +x ./build.sh
            ./build.sh

        - name: Create Release and Upload Artifacts
          uses: softprops/action-gh-release@v1
          with:
            files: dist/*
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}